name: inrfs
description: INRFS Stock Investment Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# -------------------------
# DEPENDENCIES
# -------------------------
dependencies:
  flutter:
    sdk: flutter
    dio: ^5.4.0
file_picker: ^8.0.0


  # UI & Core
  cupertino_icons: ^1.0.6
  fl_chart: ^1.1.1
  url_launcher: ^6.3.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  # PDF & File handling
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_filex: ^4.4.0

# -------------------------
# DEV DEPENDENCIES
# -------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # App icon generator (DEV ONLY)
  flutter_launcher_icons: ^0.13.1

# -------------------------
# APP ICON CONFIGURATION
# -------------------------
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png

# -------------------------
# FLUTTER CONFIGURATION
# -------------------------
flutter:
  uses-material-design: true

  assets:
    - assets/images/
